gverify: Add progress reporting for long runs

diff --git a/gverify b/gverify
--- a/gverify
+++ b/gverify
@@ -13,6 +13,7 @@ fi
 
 GOOD=0
 BAD=0
+TOTAL=0
 
 while read -r GIT_SIGNED GIT_COMMIT; do
 	case ${GIT_SIGNED} in
@@ -48,6 +49,10 @@ while read -r GIT_SIGNED GIT_COMMIT; do
 			: $(( BAD++ ))
 			;;
 	esac
+
+	if [[ $(( ++TOTAL % 100 )) -eq 0 ]]; then
+		echo "Processed ${TOTAL} commits so far: ${GOOD} commits passed, ${BAD} commits failed" >&2
+	fi
 done < <("${GV_BINDIR}"/gvgit --no-pager log --pretty='%G? %h' "${@}")
 
 if [[ ${BAD} -gt 0 ]]; then
